apiVersion: v1
kind: Namespace
metadata:
  name: abs-bookclub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abs-bookclub
  namespace: abs-bookclub
  labels:
    app: abs-bookclub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abs-bookclub
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abs-bookclub
    spec:
      containers:
      - name: app
        image: yourandomly/abs-bookclub:v1.3.0
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            name: http
        env:
          - name: BASE_URL
            value: http://audiobookshelf.audiobookshelf.svc.cluster.local/api
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: api-key
                key: API_KEY
                optional: false
          - name: VAPID_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: vapi-priv-key
                key: VAPID_PRIVATE_KEY
                optional: true
          - name: VAPID_PUBLIC_KEY
            value: "BBLw5yHHnVt_zen7rj5Im9LFes36QgvnQwxjLtlkJN358_bN6PWWEIiggyPsiYinQHnx0rXPfm9I9-XsmzSCCXU"
          - name: TZ
            value: Europe/London
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: abs-bookclub
  namespace: abs-bookclub
  labels:
    app: abs-bookclub
spec:
  selector:
    app: abs-bookclub
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: abs-bookclub
  namespace: abs-bookclub
spec:
  hostnames:
    - abs-bookclub.lab.jake-watson.co.uk
  parentRefs:
    - name: cilium-gateway-external
      namespace: default
  rules:
    - backendRefs:
        - kind: Service
          name: abs-bookclub
          port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: abs-bookclub
  namespace: abs-bookclub
spec:
  endpoints:
    - dnsName: abs-bookclub.lab.jake-watson.co.uk
      recordTTL: 300
      recordType: A
      targets:
        - 212.69.47.125
---
# ExternalSecret stub: update secretStoreRef.name and remoteRef to match your Bitwarden setup
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-key
  namespace: abs-bookclub
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: API_KEY
      remoteRef:
        key: b710d7f5-6216-4598-b765-b335000631b6  # This is the ID of the Bitwarden secret
---
# ExternalSecret stub: update secretStoreRef.name and remoteRef to match your Bitwarden setup
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vapi-priv-key
  namespace: abs-bookclub
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: VAPID_PRIVATE_KEY
      remoteRef:
        key: fc57bf0f-ee17-43ee-baff-b34d001a1df9  # This is the ID of the Bitwarden secret