apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/you-randomly/argo-cd/
    path: manifests/install-gateway-api-crds.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-api
  syncPolicy:
    automated:
      prune: true